name: Build & Release operator Image

env:
  # IMAGE_REPO: ${{ github.repository }}
  IMAGE_REPO: karmada
  IMAGE_ROOT_PATH: docker
  BUILD_PLATFORM: linux/amd64,linux/arm64
  REGISTER: ${{ secrets.REGISTRY_NAME }}
  REGISTER_USER: ${{ secrets.REGISTRY_USER }}
  REGISTER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get the version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
          VERSION=latest
        fi
        echo ::set-output name=VERSION::${VERSION}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login registry
      run: |
        echo "${{ env.REGISTER_PASSWORD }}" | docker login ${{ env.REGISTER }} -u ${{ env.REGISTER_USER }} --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: image=moby/buildkit:master

    - name: Build & Pushing operator image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.IMAGE_ROOT_PATH }}/Dockerfile
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ env.IMAGE_REPO }}
          org.opencontainers.image.revision=${{ github.sha }}
        platforms: ${{ env.BUILD_PLATFORM }}
        build-args: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
        tags: ${{ env.REGISTER }}/${{ env.IMAGE_REPO }}/karmada-operator:${{ steps.get_version.outputs.VERSION }}
        push: true
        github-token: ${{ env.REGISTER_PASSWORD }}
